package compress.joshattic.us

import android.media.MediaExtractor
import android.media.MediaFormat
import android.net.Uri
import android.os.ParcelFileDescriptor
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import compress.joshattic.us.quality.*
import org.json.JSONObject
import org.junit.Assert.*
import org.junit.Assume.assumeTrue
import org.junit.Test
import org.junit.runner.RunWith
import java.io.File

/** Synthetic controls generated by scripts/device/make_scoring_controls.py; never replaces media. */
@RunWith(AndroidJUnit4::class)
class ScoringParityDeviceTest {
    private val instrumentation = InstrumentationRegistry.getInstrumentation()
    private val context = instrumentation.targetContext

    @Test fun exactFrameControls() {
        val input = InstrumentationRegistry.getArguments().getString("scoringControls")
        assumeTrue("Supply -e scoringControls /data/local/tmp/compressor-controls; skipped is not a pass", input != null)
        require(input!!.matches(Regex("/[A-Za-z0-9_./-]+")) && !input.contains(".."))
        assertTrue("VMAF must load for parity controls", VmafNative.isAvailable)
        val work = File(context.cacheDir, "parity_controls_${System.currentTimeMillis()}").apply { mkdirs() }
        fun copy(name: String): File {
            require(name.matches(Regex("[A-Za-z0-9_.-]+")))
            val file = File(work, name)
            val pfd = instrumentation.uiAutomation.executeShellCommand("cat '$input/$name'")
            ParcelFileDescriptor.AutoCloseInputStream(pfd).use { stream -> file.outputStream().use { stream.copyTo(it) } }
            return file
        }
        val run = "selfcheck_${System.currentTimeMillis()}"
        val evidence = File(context.filesDir, "diagnostics/$run/frames")
        try {
            val manifest = JSONObject(copy("controls.json").readText())
            val files = manifest.getJSONArray("files")
            for (i in 0 until files.length()) {
                val spec = files.getJSONObject(i); val file = copy(spec.getString("name"))
                assertEquals(spec.getString("sha256"), file.inputStream().use {
                    DiagnosticsArchivePlan.copyPayload("control", it, object : java.io.OutputStream() {
                        override fun write(b: Int) {}
                        override fun write(b: ByteArray, off: Int, len: Int) {}
                    }).sha256
                })
            }
            val cases = manifest.getJSONArray("cases")
            for (i in 0 until cases.length()) {
                val spec = cases.getJSONObject(i)
                val ref = File(work, spec.getString("reference")); val dist = File(work, spec.getString("candidate"))
                val start = manifest.getLong("startUs")
                val window = ScoreWindow(start, manifest.getLong("endUs"), start + spec.optLong("distOffsetUs"),
                    contextUs = manifest.getLong("contextUs"))
                val result = VmafPairScorer.score(context, Uri.fromFile(ref), Uri.fromFile(dist), listOf(window),
                    countIdenticalFrames = true, traceRequest = FrameTraceRequest(evidence, spec.getString("id"), "1", "control",
                        mapOf("appCommit" to BuildConfig.GIT_COMMIT, "syntheticControl" to true)))
                println("PARITY_CONTROL ${spec.getString("id")} decision=${CertificationDecision.of(result)}")
                when (spec.getString("expect")) {
                    "misaligned" -> assertTrue(result is PairScoreOutcome.MisalignmentRejected)
                    "unavailable" -> assertTrue(result is PairScoreOutcome.Unavailable)
                    "different" -> {
                        val windows = result.scoredWindows
                        assertNotNull("control did not decode", windows)
                        assertTrue(windows!!.any { it.pairing?.identicalFrames != it.comparedFrames })
                    }
                    else -> {
                        assertTrue("${spec.getString("id")}: $result", result is PairScoreOutcome.Scored)
                        val windows = (result as PairScoreOutcome.Scored).windows
                        assertTrue(windows.isNotEmpty())
                        assertTrue(windows.all { it.pairing?.identicalFrames == it.comparedFrames && it.traceId != null })
                        if (spec.getString("expect") == "identical-color-tags-differ") {
                            assertNotEquals("unchanged pixels do not make different color tags safe", color(ref), color(dist))
                        }
                    }
                }
            }
            println("PARITY_EVIDENCE diagnostics/$run; export Everything after the test")
        } finally { work.deleteRecursively() }
    }

    private fun color(file: File): List<Int?> {
        val extractor = MediaExtractor()
        return try {
            extractor.setDataSource(file.absolutePath)
            val format = (0 until extractor.trackCount).map { extractor.getTrackFormat(it) }
                .first { it.getString(MediaFormat.KEY_MIME)?.startsWith("video/") == true }
            listOf(MediaFormat.KEY_COLOR_STANDARD, MediaFormat.KEY_COLOR_RANGE, MediaFormat.KEY_COLOR_TRANSFER)
                .map { if (format.containsKey(it)) format.getInteger(it) else null }
        } finally { extractor.release() }
    }
}
