"""Stable public constants for the canonical runtime."""

CORE_VERSION = "1.0.0"
SCHEMA_VERSION = "1"
PLUGIN_PACKAGE_VERSION = "0.1.0"

EXIT_COMPLETED = 0
EXIT_GATE_FAILED = 2
EXIT_INVALID_INPUT = 10
EXIT_MISSING_PREREQUISITE = 11
EXIT_IDENTITY_MISMATCH = 12
EXIT_BLOCKED = 13
EXIT_INTERNAL = 14
EXIT_IMMUTABLE_CONFLICT = 15

QUALITY_VERDICTS = frozenset({"PASS", "FAIL", "BLOCKED"})
PROCESS_STATUSES = frozenset({"DRY_RUN", "COMPLETED", "BLOCKED", "ERROR"})
